version: '3.5'

services:

  bookmark-service:
    build: ../.
    ports:
      - "18081:8081"
    restart: unless-stopped
    depends_on:
      - bookmarks-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarks-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APPLICATION_VOTE_SERVICE_URL: http://vote-service:8082
